name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Project Feedback
        run: |
          chmod u+r+x ./main/project/tests.sh
          cd ./main/project
          ./tests.sh