name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - project/**
      - data/**

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install numpy
          pip install pytest
          pip install sqlalchemy
          pip install sqlite3
      - name: Project Feedback
        run: bash ./main/project/tests.sh